name: Run Cypress Tests
on: [push]
jobs:
  full:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' || !github.event.pull_request.draft }}
    name: Full (Build, Validate, Test)
    runs-on: ubuntu-latest
    env:
      NPM_CACHE: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Prepare environment variables
        run: |
          which node
          node --version
          cp cypress.env.default.json cypress.env.json
      - name: Install dependencies
        run: |
          npm install
          npm list
      - name: Start Webpack Dev Server
        run: npm run start&
      - name: Run Cypress Tests
        run: npx cypress run
